"use client";
import type { Metadata } from "next";
import { inter, jost } from "@/app/fonts";
import "./globals.css";
import { useEffect } from "react";
import Lenis from "@studio-freight/lenis";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const lenis = new Lenis();
    function raf(time: number) {
      lenis.raf(time);
      requestAnimationFrame(raf);
    }

    requestAnimationFrame(raf);
  }, []);

  return (
    <html lang="en">
      <body className={jost.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
